language: java
jdk:
  - oraclejdk7
script: ./travis.sh
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.m2/wrapper
before_cache:
  - rm -f $HOME/.m2/repository/argelbargel/jenkins/plugins/gitlab-branch-source
deploy:
  provider: releases
  api_key: "$GITHUB_API_TOKEN"
  skip_cleanup: true
  on:
    tags: true
  file:
    - "$HOME/.m2/repository/argelbargel/jenkins/plugins/gitlab-branch-source/$TRAVIS_TAG/gitlab-branch-source-$TRAVIS_TAG.hpi"
